### ISSUE TITLE
HTML Validation

### ISSUE THREAD

**Issue by acushlakoncept** [tamsay/Leaderboard#2]
As an aspiring developer, it's a good practice to imbibe good HTML practices.
Let the HTML validator site:  https://validator.w3.org/nu/#file be always there by your side to use in validating all you HTML semantics to be sure you are on track.

Your code contains about 16 HTML errors and 1 warning.

Use the HTML validator to fix the errors.

Happy Coding 👍

**Comment by tamsay** [comment]
HTML Validation passed.
